-- 0003_universal_documents.sql
--
-- Adds universal extraction fields for non-financial documents.
-- Idempotent and safe to run multiple times.

alter table public.ad_extractions
  add column if not exists document_type text,
  add column if not exists summary text,
  add column if not exists metadata jsonb;

comment on column public.ad_extractions.document_type is
  'Universal doc type: financial|contract|legal|medical|educational|technical|correspondence|personal|media|other';
comment on column public.ad_extractions.summary is
  'Short extraction summary generated by the LLM.';
comment on column public.ad_extractions.metadata is
  'Type-specific JSON payload for non-financial documents.';

create index if not exists ad_extractions_document_type_idx
  on public.ad_extractions(document_type);
